'use client'

import React, { useState, useRef, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { updatePage, deletePage } from '@/lib/actions/pages'
import { createBlock, updateBlock, deleteBlock, reorderBlocks } from '@/lib/actions/blocks'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
    MoreHorizontal,
    Star,
    Trash2,
    Image as ImageIcon,
} from 'lucide-react'
import { Block, BlockType } from '@/components/editor/types'
import { BlockEditor } from '@/components/editor/block-editor'

// ========================================
// TYPES
// ========================================

interface PageData {
    id: string
    title: string
    icon: string | null
    coverImage: string | null
    isFavorited: boolean
    blocks: any[] // We cast this to Block[] for the editor
}

interface PageEditorProps {
    page: PageData
}

// ========================================
// PAGE EDITOR COMPONENT
// ========================================

export function PageEditor({ page }: PageEditorProps) {
    const router = useRouter()
    const [title, setTitle] = useState(page.title)
    const [icon, setIcon] = useState(page.icon || '📄')
    const [coverImage, setCoverImage] = useState(page.coverImage)
    const [isFavorited, setIsFavorited] = useState(page.isFavorited)
    const [isSaving, setIsSaving] = useState(false)
    const titleRef = useRef<HTMLInputElement>(null)
    const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null)

    // Autosave title changes
    const saveTitle = useCallback(async (newTitle: string) => {
        if (saveTimeoutRef.current) {
            clearTimeout(saveTimeoutRef.current)
        }

        saveTimeoutRef.current = setTimeout(async () => {
            setIsSaving(true)
            await updatePage(page.id, { title: newTitle })
            setIsSaving(false)
            router.refresh()
        }, 200)
    }, [page.id, router])

    const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const newTitle = e.target.value
        setTitle(newTitle)
        saveTitle(newTitle)
    }

    const handleTitleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter') {
            e.preventDefault()
            titleRef.current?.blur()
            // In a real implementation, we could focus the first block of the editor here
        }
    }

    const handleToggleFavorite = async () => {
        setIsFavorited(!isFavorited)
        await updatePage(page.id, { isFavorited: !isFavorited })
        router.refresh()
    }

    const handleDelete = async () => {
        if (confirm('Are you sure you want to delete this page?')) {
            await deletePage(page.id)
            router.push('/dashboard')
            router.refresh()
        }
    }

    const handleIconChange = async (newIcon: string) => {
        setIcon(newIcon)
        await updatePage(page.id, { icon: newIcon })
        router.refresh()
    }

    const handleAddCover = async () => {
        const defaultCover = 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'
        setCoverImage(defaultCover)
        await updatePage(page.id, { coverImage: defaultCover })
        router.refresh()
    }

    const handleRemoveCover = async () => {
        setCoverImage(null)
        await updatePage(page.id, { coverImage: null })
        router.refresh()
    }

    const handleChangeCover = async () => {
        const url = prompt('Enter image URL (Unsplash, etc):', coverImage || '')
        if (url) {
            setCoverImage(url)
            await updatePage(page.id, { coverImage: url })
            router.refresh()
        }
    }

    // Persistence Handlers for BlockEditor

    const handleCreateBlock = async (block: Block, afterBlockId?: string) => {
        console.log('Creating block:', block)
        // We pass the ID generated by the client to ensure sync
        await createBlock({
            id: block.id,
            pageId: page.id,
            type: block.type,
            content: block.content,
            parentBlockId: block.parentId, // Note: BlockEditor uses parentId, Prisma uses parentBlockId
            sortOrder: block.sortOrder // BlockEditor sets this to 0 usually, backend fixes it
        })
        router.refresh()
    }

    const handleUpdateBlock = async (id: string, updates: any) => {
        // Debounced save for content updates
        if (saveTimeoutRef.current) {
            clearTimeout(saveTimeoutRef.current)
        }

        // Immediate local state update is handled by BlockEditor
        // We just schedule server save
        saveTimeoutRef.current = setTimeout(async () => {
            // Map updates from BlockEditor to the expected format for updateBlock action
            const payload: any = {}
            if (updates.content !== undefined) payload.content = updates.content
            if (updates.type !== undefined) payload.type = updates.type
            if (updates.sortOrder !== undefined) payload.sortOrder = updates.sortOrder

            await updateBlock(id, payload)
        }, 200)
    }

    const handleDeleteBlock = async (id: string) => {
        await deleteBlock(id)
        router.refresh()
    }

    const handleReorderBlocks = async (newBlocks: Block[]) => {
        const ids = newBlocks.map(b => b.id)
        await reorderBlocks(page.id, ids)
    }

    const handleChange = async (newBlocks: Block[]) => {
        // Handled by specific events
    }

    return (
        <div className="flex-1 flex flex-col w-full h-full bg-white dark:bg-zinc-950">
            {/* Cover Image */}
            {coverImage && (
                <div className="group relative w-full h-48 md:h-60 bg-muted shrink-0">
                    <img
                        src={coverImage}
                        alt="Cover"
                        className="w-full h-full object-cover"
                    />
                    <div className="absolute bottom-4 right-8 opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
                        <Button variant="secondary" size="sm" onClick={handleChangeCover} className="text-xs h-7">
                            Change cover
                        </Button>
                        <Button variant="secondary" size="sm" onClick={handleRemoveCover} className="text-xs h-7">
                            Remove
                        </Button>
                    </div>
                </div>
            )}

            {/* Page Content Container */}
            <div className="flex-1 flex flex-col max-w-4xl mx-auto w-full">
                {/* Page Header */}
                <div className="px-8 pt-16 pb-8 group/header">
                    {/* Top Actions */}
                    <div className="flex items-center justify-between mb-8">
                        <div className="flex items-center gap-2">
                            {/* Icon Button */}
                            <div className="relative group/icon">
                                <button
                                    onClick={() => {
                                        const emojis = ['📄', '📝', '📋', '📊', '🎯', '💡', '🚀', '⭐', '📌', '🔖', '📚', '🎨']
                                        const currentIndex = emojis.indexOf(icon)
                                        const nextIndex = (currentIndex + 1) % emojis.length
                                        handleIconChange(emojis[nextIndex])
                                    }}
                                    className="text-4xl hover:bg-accent/50 rounded-lg p-2 transition-colors"
                                    title="Click to change icon"
                                >
                                    {icon}
                                </button>
                            </div>
                        </div>

                        <div className="flex items-center gap-1 opacity-0 group-hover/header:opacity-100 transition-opacity">
                            {isSaving && (
                                <span className="text-xs text-muted-foreground mr-2">Saving...</span>
                            )}
                            <Button
                                variant="ghost"
                                size="icon"
                                onClick={handleToggleFavorite}
                                className={cn(isFavorited && "text-yellow-500")}
                            >
                                <Star className={cn("h-4 w-4", isFavorited && "fill-current")} />
                            </Button>
                            <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                    <Button variant="ghost" size="icon">
                                        <MoreHorizontal className="h-4 w-4" />
                                    </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end">
                                    <DropdownMenuItem onClick={handleToggleFavorite}>
                                        <Star className="h-4 w-4 mr-2" />
                                        {isFavorited ? 'Remove from favorites' : 'Add to favorites'}
                                    </DropdownMenuItem>
                                    <DropdownMenuItem onClick={handleAddCover}>
                                        <ImageIcon className="h-4 w-4 mr-2" />
                                        Add cover image
                                    </DropdownMenuItem>
                                    <DropdownMenuSeparator />
                                    <DropdownMenuItem
                                        className="text-destructive focus:text-destructive"
                                        onClick={handleDelete}
                                    >
                                        <Trash2 className="h-4 w-4 mr-2" />
                                        Delete page
                                    </DropdownMenuItem>
                                </DropdownMenuContent>
                            </DropdownMenu>
                        </div>
                    </div>

                    {/* Title */}
                    <input
                        ref={titleRef}
                        type="text"
                        value={title}
                        onChange={handleTitleChange}
                        onKeyDown={handleTitleKeyDown}
                        placeholder="Untitled"
                        className="w-full text-4xl font-bold bg-transparent border-none outline-none placeholder:text-muted-foreground/50 focus:ring-0"
                    />
                </div>

                {/* Block Editor */}
                <div className="flex-1 px-8 pb-16">
                    <BlockEditor
                        initialBlocks={page.blocks as Block[]}
                        onCreateBlock={handleCreateBlock}
                        onUpdateBlock={handleUpdateBlock}
                        onDeleteBlock={handleDeleteBlock}
                        onReorderBlocks={handleReorderBlocks}
                    />
                </div>
            </div>
        </div>
    )
}
